package theme

import (
	"fmt"
	"strings"
)

const genHeader = "generated by `dotfiles theme` — do not edit, switching themes overwrites it"

// Wezterm renders ~/.config/wezterm/theme.lua; wezterm.lua requires it and
// falls back to its built-in scheme when absent. wezterm auto-reloads.
func Wezterm(p *Palette) string {
	var b strings.Builder
	fmt.Fprintf(&b, "-- %s\n-- theme: %s (%s)\nreturn {\n\tname = %q,\n\tcolors = {\n", genHeader, p.Name, p.Label, p.Name)
	fmt.Fprintf(&b, "\t\tforeground = %q,\n\t\tbackground = %q,\n", p.Primary.Foreground, p.Primary.Background)
	fmt.Fprintf(&b, "\t\tcursor_bg = %q,\n\t\tcursor_fg = %q,\n\t\tcursor_border = %q,\n", p.Cursor.Cursor, p.Cursor.Text, p.Cursor.Cursor)
	fmt.Fprintf(&b, "\t\tselection_fg = %q,\n\t\tselection_bg = %q,\n", p.Selection.Text, p.Selection.Background)
	ansi := func(key string, a *ANSI) {
		fmt.Fprintf(&b, "\t\t%s = {\n", key)
		for _, c := range []string{a.Black, a.Red, a.Green, a.Yellow, a.Blue, a.Magenta, a.Cyan, a.White} {
			fmt.Fprintf(&b, "\t\t\t%q,\n", c)
		}
		b.WriteString("\t\t},\n")
	}
	ansi("ansi", &p.Normal)
	ansi("brights", &p.Bright)
	b.WriteString("\t},\n}\n")
	return b.String()
}

// ZellijTheme renders themes/<name>.kdl (committed repo asset).
func ZellijTheme(p *Palette) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// %s (%s) — generated from themes/%s/palette.toml, do not edit by hand\nthemes {\n    %s {\n", p.Label, p.Source, p.Name, p.Name)
	rows := [][2]string{
		{"fg", p.Primary.Foreground}, {"bg", p.Primary.Background},
		{"black", p.Normal.Black}, {"red", p.Normal.Red}, {"green", p.Normal.Green},
		{"yellow", p.Normal.Yellow}, {"blue", p.Normal.Blue}, {"magenta", p.Normal.Magenta},
		{"cyan", p.Normal.Cyan}, {"white", p.Normal.White}, {"orange", p.Roles.Warn},
	}
	for _, r := range rows {
		fmt.Fprintf(&b, "        %s %q\n", r[0], r[1])
	}
	b.WriteString("    }\n}\n")
	return b.String()
}

// ZjstatusLayout renders the live zellij layouts/default.kdl with the
// palette applied to the status-bar colors.
func ZjstatusLayout(p *Palette) string {
	repl := strings.NewReplacer(
		"{{accent}}", p.Roles.Accent,
		"{{warn}}", p.Roles.Warn,
		"{{error}}", p.Roles.Error,
		"{{dim}}", p.Roles.Dim,
		"{{line}}", p.Roles.Line,
		"{{sel}}", p.Roles.Sel,
	)
	return "// " + genHeader + " (theme: " + p.Name + ")\n" + repl.Replace(zjstatusTemplate)
}

// zjstatusTemplate is the repo's layouts/default.kdl with colors tokenized.
// Keep structure in sync with zellij/layouts/default.kdl.
const zjstatusTemplate = `layout {
    tab name="agent" {
      pane
    }

    tab name="nvim" focus=true {
        pane
    }

    tab name="shell" {
        pane
    }

    default_tab_template {
        pane size=1 borderless=true {
            plugin location="file:~/.config/zellij/plugins/zjstatus.wasm" {
                format_left   "{mode} #[fg={{error}},bold]{session}{tabs}"
                format_right  "{command_git_branch} {datetime}"
                format_space  ""

                border_enabled  "false"
                border_char     "─"
                border_format   "#[fg={{line}}]{char}"
                border_position "top"

                hide_frame_for_single_pane "true"
                mode_normal  "#[bg={{sel}}] "
                mode_tmux    "#[bg={{error}}] "

                tab_normal   "#[fg={{dim}}] {name} "
                tab_active   "#[fg={{accent}},bold,italic] {name} "

                command_git_branch_command     "git rev-parse --abbrev-ref HEAD"
                command_git_branch_format      "#[fg={{warn}}] {stdout} "
                command_git_branch_interval    "10"
                command_git_branch_rendermode  "static"

                datetime        "#[fg={{dim}},bold] {format} "
                datetime_format "%A, %d %b %Y %H:%M"
                datetime_timezone "America/Bogota"
            }
        }
        children
        pane size=1 borderless=true  {
            plugin location="zellij:status-bar"
        }
    }
}
`

// NvimActive renders ~/.config/nvim/lua/config/theme-active.lua, read by
// nvim/lua/plugins/colorscheme.lua (falls back to ayu-dark when absent).
func NvimActive(p *Palette) string {
	return fmt.Sprintf("-- %s\nreturn { colorscheme = %q }\n", genHeader, p.Nvim)
}

// ZshEnv renders ~/.config/zsh/00-theme.zsh (sourced first by the modular
// loop in .zshrc). BAT_THEME=ansi makes bat inherit the terminal palette so
// it matches every theme with no extra assets.
func ZshEnv(p *Palette) string {
	fzf := strings.Join([]string{
		"bg:" + p.Primary.Background, "fg:" + p.Primary.Foreground,
		"bg+:" + p.Roles.Sel, "fg+:" + p.Primary.Foreground,
		"hl:" + p.Roles.Accent, "hl+:" + p.Roles.Accent,
		"info:" + p.Roles.Dim, "border:" + p.Roles.Line,
		"prompt:" + p.Roles.Accent2, "pointer:" + p.Roles.Accent,
		"marker:" + p.Roles.Good, "spinner:" + p.Roles.Accent2,
		"header:" + p.Roles.Dim,
	}, ",")
	return fmt.Sprintf("# %s\n# theme: %s (%s)\nexport BAT_THEME=ansi\nexport FZF_DEFAULT_OPTS=\"--color=%s\"\n", genHeader, p.Name, p.Label, fzf)
}

// YaziFlavor renders flavors/<name>.yazi/flavor.toml (committed repo asset).
// Same schema as theme.toml; structure mirrors the hand-tuned Ayu file.
func YaziFlavor(p *Palette) string {
	r := p.Roles
	return fmt.Sprintf(`# %s (%s) — generated from themes/%s/palette.toml, do not edit by hand
#
# app.overall.bg is REQUIRED, not cosmetic: yazi's image_erase() paints spaces
# in this colour to clear an image before drawing a modal over it. Leaving it
# unset (the upstream default) makes previews bleed through dialogs.

[app]
overall = { bg = "%s" }

[mgr]
cwd = "%s"

hovered = { bg = "%s", bold = true }

find_keyword  = { fg = "%s", bold = true }
find_position = { fg = "%s", bold = true }

marker_copied   = { fg = "%s", bg = "%s" }
marker_cut      = { fg = "%s", bg = "%s" }
marker_marked   = { fg = "%s", bg = "%s" }
marker_selected = { fg = "%s", bg = "%s" }

count_copied   = { fg = "%s", bg = "%s" }
count_cut      = { fg = "%s", bg = "%s" }
count_selected = { fg = "%s", bg = "%s" }

border_symbol = "│"
border_style  = { fg = "%s" }

[status]
overall = { bg = "%s" }

perm_sep   = { fg = "%s" }
perm_type  = { fg = "%s" }
perm_read  = { fg = "%s" }
perm_write = { fg = "%s" }
perm_exec  = { fg = "%s" }

[input]
border   = { fg = "%s" }
title    = {}
value    = {}
selected = { bg = "%s" }

[pick]
border   = { fg = "%s" }
active   = { fg = "%s", bold = true }
inactive = {}

[which]
mask            = { bg = "%s" }
cand            = { fg = "%s" }
rest            = { fg = "%s" }
desc            = { fg = "%s" }
separator       = "  "
separator_style = { fg = "%s" }

[tasks]
border  = { fg = "%s" }
title   = {}
hovered = { fg = "%s", underline = true }

[notify]
title_info  = { fg = "%s" }
title_warn  = { fg = "%s" }
title_error = { fg = "%s" }

[confirm]
border  = { fg = "%s", bg = "%s" }
title   = { fg = "%s", bg = "%s" }
body    = { bg = "%s" }
list    = { fg = "%s", bg = "%s" }

[filetype]
rules = [
  # Media
  { mime = "**/image/*", fg = "%s" },
  { mime = "**/{audio,video}/*", fg = "%s" },
  # Archives / packages
  { mime = "**/application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "%s" },
  { url = "*.{apk,ipa,dmg,pkg}", fg = "%s" },
  # Documents
  { mime = "**/application/{pdf,doc,rtf}", fg = "%s" },
  { url = "*.{md,txt,rst}", fg = "%s" },
  # Code / config
  { url = "*.{js,ts,tsx,jsx,lua,py,go,rs,rb,sh,zsh}", fg = "%s" },
  { url = "*.{json,yaml,yml,toml,kdl,ini,conf}", fg = "%s" },
  # Virtual file system
  { mime = "vfs/{absent,stale}", fg = "%s" },
  # Special
  { url = "*", is = "orphan", fg = "%s" },
  { url = "*", is = "exec", fg = "%s" },
  # Fallback
  { url = "*/", fg = "%s" },
  { url = "*", fg = "%s" }
]
`,
		p.Label, p.Source, p.Name,
		p.Primary.Background,
		r.Accent2,
		r.Sel,
		r.Accent, p.Bright.Magenta,
		r.Good, r.Good, r.Error, r.Error, r.Accent2, r.Accent2, r.Accent, r.Accent,
		p.Primary.Background, r.Good, p.Primary.Background, r.Error, p.Primary.Background, r.Accent,
		r.Line,
		p.Primary.Background,
		r.Dim, r.Good, r.Accent, r.Error, p.Bright.Cyan,
		r.Accent2, r.Sel,
		r.Accent2, r.Accent,
		r.Panel, p.Bright.Cyan, r.Dim, p.Bright.Magenta, r.Line,
		r.Accent2, r.Accent,
		p.Bright.Cyan, r.Warn, r.Error,
		r.Accent2, p.Primary.Background, r.Accent2, p.Primary.Background, p.Primary.Background, p.Bright.Cyan, p.Primary.Background,
		p.Bright.Magenta, r.Accent,
		r.Warn, r.Warn,
		r.Error, p.Primary.Foreground,
		r.Good, p.Bright.Cyan,
		r.Dim,
		r.Error, r.Good,
		r.Accent2, p.Primary.Foreground,
	)
}

// BtopTheme renders themes/<name>.theme (committed repo asset).
func BtopTheme(p *Palette) string {
	r := p.Roles
	rows := [][2]string{
		{"main_bg", p.Primary.Background}, {"main_fg", p.Primary.Foreground},
		{"title", p.Primary.Foreground}, {"hi_fg", r.Accent},
		{"selected_bg", r.Sel}, {"selected_fg", r.Accent},
		{"inactive_fg", r.Dim}, {"graph_text", r.Dim},
		{"meter_bg", r.Line}, {"proc_misc", r.Accent2},
		{"cpu_box", r.Line}, {"mem_box", r.Line}, {"net_box", r.Line}, {"proc_box", r.Line},
		{"div_line", r.Line},
		{"temp_start", r.Good}, {"temp_mid", r.Warn}, {"temp_end", r.Error},
		{"cpu_start", r.Good}, {"cpu_mid", r.Warn}, {"cpu_end", r.Error},
		{"free_start", r.Good}, {"free_mid", r.Warn}, {"free_end", r.Error},
		{"cached_start", r.Accent2}, {"cached_mid", r.Accent2}, {"cached_end", p.Bright.Cyan},
		{"available_start", r.Good}, {"available_mid", r.Warn}, {"available_end", r.Error},
		{"used_start", r.Good}, {"used_mid", r.Warn}, {"used_end", r.Error},
		{"download_start", r.Good}, {"download_mid", r.Accent2}, {"download_end", p.Bright.Magenta},
		{"upload_start", r.Warn}, {"upload_mid", r.Error}, {"upload_end", p.Bright.Magenta},
		{"process_start", r.Good}, {"process_mid", r.Warn}, {"process_end", r.Error},
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# %s (%s) — generated from themes/%s/palette.toml, do not edit by hand\n", p.Label, p.Source, p.Name)
	for _, row := range rows {
		fmt.Fprintf(&b, "theme[%s]=\"%s\"\n", row[0], row[1])
	}
	return b.String()
}

// GhDashThemeBlock renders the `theme:` block for gh-dash's config.yml.
func GhDashThemeBlock(p *Palette) string {
	r := p.Roles
	return fmt.Sprintf(`theme:
  # %s (theme: %s)
  ui:
    table:
      showSeparator: true
      compact: false
  colors:
    text:
      primary: "%s"
      secondary: "%s"
      inverted: "%s"
      faint: "%s"
      warning: "%s"
      success: "%s"
      error: "%s"
    background:
      selected: "%s"
    border:
      primary: "%s"
      secondary: "%s"
      faint: "%s"
`, genHeader, p.Name,
		p.Primary.Foreground, r.Accent2, p.Primary.Background, r.Dim, r.Warn, r.Good, r.Error,
		r.Sel, r.Accent2, r.Line, r.Panel)
}

// VisiData renders ~/.visidata/theme.py, exec'd by the repo's .visidatarc
// when present (absent = VisiData's own defaults).
//
// VisiData colors are xterm-256 indices or the 8 ANSI names, never hex, and
// its stock theme leans on `black`/`white` — which the terminal remaps to the
// active palette, so a theme whose ANSI black is a mid grey paints the whole
// sheet grey. Every color here is therefore a fixed cube index derived from
// the palette (see Xterm256), independent of the ANSI remapping.
func VisiData(p *Palette) string {
	r := p.Roles
	c := Xterm256
	fg, bg := c(p.Primary.Foreground), c(p.Primary.Background)
	panel, line, dim := c(r.Panel), c(r.Line), c(r.Dim)
	accent, accent2 := c(r.Accent), c(r.Accent2)
	good, warn, bad := c(r.Good), c(r.Warn), c(r.Error)
	sel := c(r.Sel)
	// current column: a shade off the background, so it reads under the row cursor
	col := c(Mix(p.Primary.Background, p.Primary.Foreground, 0.10))
	readonly := c(Mix(p.Primary.Background, r.Error, 0.25))

	opts := [][2]string{
		// sheet body
		{"color_default", fmt.Sprintf("%d on %d", fg, bg)},
		{"color_default_hdr", fmt.Sprintf("bold %d on %d", accent, panel)},
		{"color_bottom_hdr", fmt.Sprintf("underline %d on %d", fg, panel)},
		{"color_current_hdr", fmt.Sprintf("bold %d on %d", bg, accent)},
		{"color_column_sep", fmt.Sprintf("%d on %d", line, bg)},
		{"color_key_col", fmt.Sprintf("%d", accent2)},
		{"color_hidden_col", fmt.Sprintf("%d", dim)},
		{"color_current_row", fmt.Sprintf("on %d", sel)},
		{"color_current_col", fmt.Sprintf("on %d", col)},
		{"color_selected_row", fmt.Sprintf("%d", accent)},
		{"color_readonly", fmt.Sprintf("on %d", readonly)},
		// menu bar and helpbox
		{"color_menu", fmt.Sprintf("%d on %d", fg, panel)},
		{"color_menu_active", fmt.Sprintf("bold %d on %d", bg, accent)},
		{"color_menu_spec", fmt.Sprintf("%d on %d", good, panel)},
		{"color_menu_help", fmt.Sprintf("italic %d on %d", fg, panel)},
		// status bars, sidebar, command palette
		{"color_status", fmt.Sprintf("%d on %d", fg, panel)},
		{"color_active_status", fmt.Sprintf("bold %d on %d", bg, accent2)},
		{"color_inactive_status", fmt.Sprintf("%d on %d", dim, panel)},
		{"color_top_status", fmt.Sprintf("underline %d on %d", fg, panel)},
		{"color_highlight_status", fmt.Sprintf("%d on %d", bg, good)},
		{"color_status_replay", fmt.Sprintf("%d", good)},
		{"color_longname_status", fmt.Sprintf("%d", dim)},
		{"color_longname_guide", fmt.Sprintf("%d", dim)},
		{"color_guide_unwritten", fmt.Sprintf("%d on %d", dim, bg)},
		{"color_sidebar", fmt.Sprintf("%d on %d", fg, panel)},
		{"color_sidebar_title", fmt.Sprintf("bold %d on %d", bg, accent)},
		{"color_cmdpalette", fmt.Sprintf("%d on %d", fg, panel)},
		{"color_match", fmt.Sprintf("bold %d", accent)},
		{"color_highlight_search", fmt.Sprintf("bold %d on %d", bg, accent)},
		{"color_aggregator", fmt.Sprintf("bold %d on %d", accent2, panel)},
		{"color_heading", fmt.Sprintf("bold %d on %d", bg, accent)},
		{"color_code", fmt.Sprintf("bold %d on %d", accent2, panel)},
		{"color_keystrokes", fmt.Sprintf("bold %d on %d", accent, panel)},
		// editing and pending edits
		{"color_edit_cell", fmt.Sprintf("%d on %d", bg, accent2)},
		{"color_edit_unfocused", fmt.Sprintf("%d on %d", dim, panel)},
		{"color_add_pending", fmt.Sprintf("%d", good)},
		{"color_change_pending", fmt.Sprintf("reverse %d", warn)},
		{"color_delete_pending", fmt.Sprintf("%d", bad)},
		{"color_note_pending", fmt.Sprintf("bold %d", good)},
		{"color_note_row", fmt.Sprintf("%d", warn)},
		{"color_note_type", fmt.Sprintf("%d", accent)},
		// messages and graphs
		{"color_error", fmt.Sprintf("%d", bad)},
		{"color_warning", fmt.Sprintf("%d", warn)},
		{"color_working", fmt.Sprintf("%d", good)},
		{"color_currency_neg", fmt.Sprintf("%d", bad)},
		{"color_graph_axis", fmt.Sprintf("bold %d", dim)},
		{"color_graph_hidden", fmt.Sprintf("%d", dim)},
		{"color_graph_selected", fmt.Sprintf("bold %d", accent)},
	}

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n# theme: %s (%s)\nfrom visidata import vd\n\n", genHeader, p.Name, p.Label)
	for _, o := range opts {
		fmt.Fprintf(&b, "vd.options.%s = %q\n", o[0], o[1])
	}
	return b.String()
}
