// Package redact turns a secret-bearing shell file into a committable template.
package redact

import (
	"bufio"
	"bytes"
	"regexp"
	"strings"
)

// assign matches `export VAR=...`, `VAR=...`, `typeset/local/readonly VAR=...`.
var assign = regexp.MustCompile(`^(\s*(?:export|typeset|local|readonly|declare)?\s*(?:-[a-zA-Z]+\s+)?[A-Za-z_][A-Za-z0-9_]*=)(.*)$`)

// PublicMarker on a line keeps its value verbatim.
const PublicMarker = "# public"

// Template blanks every assignment value unless the line carries PublicMarker.
// Output ends with a header comment so a reader knows the file is generated.
func Template(src []byte) []byte {
	var out bytes.Buffer
	out.WriteString("# TEMPLATE generated by `dotfiles backup` — values were removed.\n")
	out.WriteString("# Fill in and save as the real file (chmod 600). Lines marked `# public` keep their value.\n")
	sc := bufio.NewScanner(bytes.NewReader(src))
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		if m := assign.FindStringSubmatch(line); m != nil && !strings.Contains(line, PublicMarker) {
			out.WriteString(m[1])
			out.WriteString("\n")
			continue
		}
		out.WriteString(line)
		out.WriteString("\n")
	}
	return out.Bytes()
}

// Suffix is appended to the repo-side filename of a secret file.
const Suffix = ".template"
